export const eras = [
  {
    age: '慶応',
    name: '孝明天皇',
    years: 1865,
    reason: '明治維新による改元',
  },
  {
    age: '天保',
    name: '仁孝天皇',
    years: 1831,
    reason: '江戸の大火や<br>京都の地震による改元',
  },
  {
    age: '安政',
    name: '孝明天皇',
    years: 1855,
    reason: '黒船来訪による改元',
  },
  {
    age: '文政',
    name: '仁孝天皇',
    years: 1818,
    reason: '仁孝天皇践祚による改元',
  },
  {
    age: '寛政',
    name: '光格天皇',
    years: 1789,
    reason: '内裏炎上などによる改元',
  },
  {
    age: '天明',
    name: '光格天皇',
    years: 1781,
    reason: '光格天皇践祚による改元',
  },
  {
    age: '安永',
    name: '後桃園天皇',
    years: 1772,
    reason: '後桃園天皇践祚による改元',
  },
  {
    age: '明和',
    name: '後桜町天皇',
    years: 1764,
    reason: '後桜町天皇践祚による改元',
  },
  {
    age: '宝暦',
    name: '桃園天皇',
    years: 1751,
    reason: '桜町上皇崩御と<br>徳川吉宗死去による改元',
  },
  {
    age: '寛延',
    name: '桃園天皇',
    years: 1748,
    reason: '桃園天皇践祚による改元',
  },
  {
    age: '延享',
    name: '桜町天皇',
    years: 1744,
    reason: '甲子革令による改元',
  },
  {
    age: '寛保',
    name: '桜町天皇',
    years: 1741,
    reason: '辛酉革命による改元',
  },
  {
    age: '元文',
    name: '桜町天皇',
    years: 1736,
    reason: '桜町天皇践祚による改元',
  },
  {
    age: '享保',
    name: '中御門天皇',
    years: 1716,
    reason: '徳川家継死去による改元',
  },
  {
    age: '正徳',
    name: '中御門天皇',
    years: 1711,
    reason: '中御門天皇践祚による改元',
  },
  {
    age: '宝永',
    name: '東山天皇',
    years: 1704,
    reason: '元禄地震による改元',
  },
  {
    age: '元禄',
    name: '東山天皇',
    years: 1688,
    reason: '東山天皇践祚による改元',
  },
  {
    age: '貞享',
    name: '霊元天皇',
    years: 1684,
    reason: '甲子革令による改元',
  },
  {
    age: '天和',
    name: '霊元天皇',
    years: 1681,
    reason: '辛酉革命による改元',
  },
  {
    age: '延宝',
    name: '霊元天皇',
    years: 1673,
    reason: '京都大火などの災異による改元',
  },
  {
    age: '寛文',
    name: '後西天皇',
    years: 1661,
    reason: '内裏火災などの災異による改元',
  },
  {
    age: '万治',
    name: '後西天皇',
    years: 1658,
    reason: '江戸の大火（明暦の大火）<br>などの災異による改元',
  },
  {
    age: '明暦',
    name: '後西天皇',
    years: 1655,
    reason: '後西天皇践祚による改元',
  },
  {
    age: '承応',
    name: '後光明天皇',
    years: 1652,
    reason: '徳川家綱将軍就任のため<br>による改元とみられている。',
  },
  {
    age: '慶安',
    name: '後光明天皇',
    years: 1648,
    reason: '「正保」が「焼亡」に繋がると<br>批判が起きたことによる改元',
  },
  {
    age: '正保',
    name: '後光明天皇',
    years: 1645,
    reason: '後光明天皇践祚による改元',
  },
  {
    age: '寛永',
    name: '後水尾天皇',
    years: 1624,
    reason: '甲子革令による改元',
  },
  {
    age: '元和',
    name: '後水尾天皇',
    years: 1615,
    reason: '後水尾天皇践祚と戦乱（大坂の役）<br>などの災異による改元',
  },
  {
    age: '慶長',
    name: '後陽成天皇',
    years: 1596,
    reason: '慶長伏見地震など<br>天変地異の災異による改元',
  },
  {
    age: '文禄',
    name: '後陽成天皇',
    years: 1593,
    reason: '後陽成天皇践祚による改元',
  },
  {
    age: '天正',
    name: '正親町天皇',
    years: 1573,
    reason: '戦乱などの災異による改元',
  },
  {
    age: '元亀',
    name: '正親町天皇',
    years: 1570,
    reason: '戦乱などの災異による改元',
  },
  {
    age: '永禄',
    name: '正親町天皇',
    years: 1558,
    reason: '正親町天皇践祚による改元',
  },
  {
    age: '弘治',
    name: '後奈良天皇',
    years: 1555,
    reason: '戦乱などの災異による改元',
  },
  {
    age: '天文',
    name: '後奈良天皇',
    years: 1532,
    reason: '戦乱などの災異による改元',
  },
  {
    age: '享禄',
    name: '後奈良天皇',
    years: 1528,
    reason: '後奈良天皇践祚による改元',
  },
  {
    age: '大永',
    name: '後柏原天皇',
    years: 1521,
    reason: '戦乱、天変などの災異による改元',
  },
  {
    age: '永正',
    name: '後柏原天皇',
    years: 1504,
    reason: '甲子革令による改元',
  },
  {
    age: '文亀',
    name: '後柏原天皇',
    years: 1501,
    reason: '後柏原天皇践祚、および辛酉革命による改元',
  },
  {
    age: '明応',
    name: '後土御門天皇',
    years: 1492,
    reason: '疫病などによる改元',
  },
  {
    age: '延徳',
    name: '後土御門天皇',
    years: 1489,
    reason: '(不明)',
  },
  {
    age: '長享',
    name: '後土御門天皇',
    years: 1487,
    reason: '戦乱や疫病などによる改元',
  },
  {
    age: '文明',
    name: '後土御門天皇',
    years: 1469,
    reason: '災異による改元',
  },
  {
    age: '応仁',
    name: '後土御門天皇',
    years: 1467,
    reason: '災異による改元',
  },
  {
    age: '文正',
    name: '後土御門天皇',
    years: 1466,
    reason: '後土御門天皇践祚による改元',
  },
  {
    age: '寛正',
    name: '後花園天皇',
    years: 1461,
    reason: '飢饉による改元',
  },
  {
    age: '腸禄',
    name: '後花園天皇',
    years: 1457,
    reason: '(不明)',
  },
  {
    age: '康正',
    name: '後花園天皇',
    years: 1455,
    reason: '(不明)',
  },
  {
    age: '享徳',
    name: '後花園天皇',
    years: 1452,
    reason: '三合の厄を避けるためによる改元',
  },
  {
    age: '宝徳',
    name: '後花園天皇',
    years: 1449,
    reason: '(不明)',
  },
  {
    age: '文安',
    name: '後花園天皇',
    years: 1444,
    reason: '甲子革令による改元',
  },
  {
    age: '嘉吉',
    name: '後花園天皇',
    years: 1441,
    reason: '辛酉革命による改元',
  },
  {
    age: '永享',
    name: '後花園天皇',
    years: 1429,
    reason: '後花園天皇践祚による改元',
  },
  {
    age: '正長',
    name: '称光天皇',
    years: 1428,
    reason: '称光天皇践祚による改元',
  },
  {
    age: '応永',
    name: '後小松天皇',
    years: 1394,
    reason: '疫病（疱瘡）の流行による改元',
  },
  {
    age: '明徳',
    name: '後小松天皇',
    years: 1390,
    reason: '天変や兵革による改元',
  },
  {
    age: '康応',
    name: '後小松天皇',
    years: 1389,
    reason: '病事による改元とみられている',
  },
  {
    age: '嘉慶',
    name: '後小松天皇',
    years: 1387,
    reason: '疫病による改元',
  },
  {
    age: '至徳',
    name: '後小松天皇',
    years: 1384,
    reason: '甲子革令による改元',
  },
  {
    age: '永徳',
    name: '後円融天皇',
    years: 1381,
    reason: '辛酉革命による改元',
  },
  {
    age: '康暦',
    name: '後円融天皇',
    years: 1379,
    reason: '疫病や兵革による改元',
  },
  {
    age: '永和',
    name: '後円融天皇',
    years: 1375,
    reason: '後円融天皇践祚による改元',
  },
  {
    age: '応安',
    name: '後光厳天皇',
    years: 1368,
    reason: '疫病や天変による改元',
  },
  {
    age: '貞治',
    name: '後光厳天皇',
    years: 1362,
    reason: '天変や兵革による改元',
  },
  {
    age: '康安',
    name: '後光厳天皇',
    years: 1361,
    reason: '(不明)',
  },
  {
    age: '延文',
    name: '後光厳天皇',
    years: 1356,
    reason: '兵革による改元',
  },
  {
    age: '文和',
    name: '後光厳天皇',
    years: 1352,
    reason: '後光厳天皇践祚による改元',
  },
  {
    age: '観応',
    name: '崇光天皇',
    years: 1350,
    reason: '崇光天皇践祚による改元',
  },
  {
    age: '貞和',
    name: '光明天皇',
    years: 1345,
    reason: '天変や疫病による改元',
  },
  {
    age: '康永',
    name: '光明天皇',
    years: 1342,
    reason: '天変や疫病による改元',
  },
  {
    age: '暦応',
    name: '光明天皇',
    years: 1338,
    reason: '(不明)',
  },
  {
    age: '元中',
    name: '後亀山天皇',
    years: 1384,
    reason: '後亀山天皇践祚<br>および甲子革令による改元',
  },
  {
    age: '弘和',
    name: '長慶天皇',
    years: 1381,
    reason: '辛酉革命による改元',
  },
  {
    age: '天授',
    name: '長慶天皇',
    years: 1375,
    reason: '地震災害による改元',
  },
  {
    age: '文中',
    name: '長慶天皇',
    years: 1372,
    reason: '災異による改元',
  },
  {
    age: '建徳',
    name: '長慶天皇',
    years: 1370,
    reason: '長慶天皇践祚による改元とみられている',
  },
  {
    age: '正平',
    name: '後村上天皇',
    years: 1347,
    reason: '天変や兵革による改元',
  },
  {
    age: '興国',
    name: '後村上天皇',
    years: 1340,
    reason: '後村上天皇践祚による<br>改元とみられている',
  },
  {
    age: '延元',
    name: '後醍醐天皇',
    years: 1336,
    reason: '建武の乱による改元',
  },
  {
    age: '元徳',
    name: '後醍醐天皇',
    years: 1329,
    reason: '疫病による改元',
  },
  {
    age: '嘉暦',
    name: '後醍醐天皇',
    years: 1326,
    reason: '疫病と地震による改元',
  },
  {
    age: '正中',
    name: '後醍醐天皇',
    years: 1324,
    reason: '甲子革令による改元',
  },
  {
    age: '元亨',
    name: '後醍醐天皇',
    years: 1321,
    reason: '辛酉革命による改元',
  },
  {
    age: '元応',
    name: '後醍醐天皇',
    years: 1319,
    reason: '後醍醐天皇践祚による改元',
  },
  {
    age: '文保',
    name: '花園天皇',
    years: 1317,
    reason: '大地震などによる改元',
  },
  {
    age: '正和',
    name: '花園天皇',
    years: 1312,
    reason: '天変地震による改元',
  },
  {
    age: '応長',
    name: '花園天皇',
    years: 1311,
    reason: '疫病による改元',
  },
  {
    age: '延慶',
    name: '花園天皇',
    years: 1308,
    reason: '花園天皇践祚による改元',
  },
  {
    age: '徳治',
    name: '後二条天皇',
    years: 1307,
    reason: '天変による改元',
  },
  {
    age: '嘉元',
    name: '後二条天皇',
    years: 1303,
    reason: '彗星と日照りによる改元',
  },
  {
    age: '乾元',
    name: '後二条天皇',
    years: 1302,
    reason: '後二条天皇践祚による改元',
  },
  {
    age: '正安',
    name: '後伏見天皇',
    years: 1299,
    reason: '後伏見天皇践祚による改元',
  },
  {
    age: '永仁',
    name: '伏見天皇',
    years: 1293,
    reason: '天変と関東の地震による改元',
  },
  {
    age: '正応',
    name: '伏見天皇',
    years: 1288,
    reason: '伏見天皇践祚による改元',
  },
  {
    age: '弘安',
    name: '後宇多天皇',
    years: 1278,
    reason: '疫病による改元とみられている',
  },
  {
    age: '建治',
    name: '後宇多天皇',
    years: 1275,
    reason: '(不明)',
  },
  {
    age: '文永',
    name: '亀山天皇',
    years: 1264,
    reason: '甲子革令による改元',
  },
  {
    age: '弘長',
    name: '亀山天皇',
    years: 1261,
    reason: '辛酉革命による改元',
  },
  {
    age: '文応',
    name: '亀山天皇',
    years: 1260,
    reason: '亀山天皇践祚による改元',
  },
  {
    age: '正元',
    name: '後深草天皇',
    years: 1259,
    reason: '(不明)',
  },
  {
    age: '正嘉',
    name: '後深草天皇',
    years: 1257,
    reason: '太政官庁などの施設の<br>焼失が相次いだことによる改元。',
  },
  {
    age: '康元',
    name: '後深草天皇',
    years: 1256,
    reason: '赤斑瘡による改元とみられている',
  },
  {
    age: '建長',
    name: '後深草天皇',
    years: 1249,
    reason: '天変や火災による改元',
  },
  {
    age: '宝治',
    name: '後深草天皇',
    years: 1247,
    reason: '後深草天皇践祚による改元',
  },
  {
    age: '寛元',
    name: '後嵯峨天皇',
    years: 1243,
    reason: '後嵯峨天皇践祚による改元',
  },
  {
    age: '仁治',
    name: '四条天皇',
    years: 1240,
    reason: '彗星、地震、旱魃などによる改元',
  },
  {
    age: '延応',
    name: '四条天皇',
    years: 1239,
    reason: '天変や地震による改元',
  },
  {
    age: '歴仁',
    name: '四条天皇',
    years: 1238,
    reason: '天変による改元',
  },
  {
    age: '嘉禎',
    name: '四条天皇',
    years: 1235,
    reason: '地震頻発による改元',
  },
  {
    age: '文暦',
    name: '四条天皇',
    years: 1234,
    reason: '天変地震による改元',
  },
  {
    age: '天福',
    name: '四条天皇',
    years: 1233,
    reason: '(不明)',
  },
  {
    age: '貞永',
    name: '後堀河天皇',
    years: 1232,
    reason: '(不明)',
  },
  {
    age: '寛喜',
    name: '後堀河天皇',
    years: 1229,
    reason: '天災、飢饉による改元',
  },
  {
    age: '安貞',
    name: '後堀河天皇',
    years: 1228,
    reason: '天変が相次いだため、<br>また、三合や疱瘡の流行による改元',
  },
  {
    age: '嘉禄',
    name: '後堀河天皇',
    years: 1225,
    reason: '通常は疱瘡によると解されている',
  },
  {
    age: '元仁',
    name: '後堀河天皇',
    years: 1224,
    reason: '天変炎旱による改元',
  },
  {
    age: '貞応',
    name: '後堀河天皇',
    years: 1222,
    reason: '後堀河天皇践祚による改元',
  },
  {
    age: '承久',
    name: '順徳天皇',
    years: 1219,
    reason: '旱魃と三合による改元',
  },
  {
    age: '建保',
    name: '順徳天皇',
    years: 1214,
    reason: '地震による改元と見られている',
  },
  {
    age: '建歴',
    name: '順徳天皇',
    years: 1211,
    reason: '順徳天皇践祚による改元',
  },
  {
    age: '承元',
    name: '土御門天皇',
    years: 1207,
    reason: '三合を原因とする説<br>疱瘡を原因とする説',
  },
  {
    age: '建永',
    name: '土御門天皇',
    years: 1206,
    reason: '赤斑瘡を原因とする説<br>摂政・九条良通の急死を原因とする説',
  },
  {
    age: '元久',
    name: '土御門天皇',
    years: 1204,
    reason: '甲子革令による改元',
  },
  {
    age: '建仁',
    name: '土御門天皇',
    years: 1201,
    reason: '辛酉革命による改元',
  },
  {
    age: '正治',
    name: '土御門天皇',
    years: 1199,
    reason: '土御門天皇践祚による改元',
  },
  {
    age: '建久',
    name: '後鳥羽天皇',
    years: 1190,
    reason: '三合による改元',
  },
  {
    age: '文治',
    name: '後鳥羽天皇',
    years: 1185,
    reason: '地震（文治地震）による改元',
  },
  {
    age: '元暦',
    name: '後鳥羽天皇',
    years: 1184,
    reason: '後鳥羽天皇践祚による改元',
  },
  {
    age: '寿永',
    name: '安徳天皇',
    years: 1182,
    reason: '飢饉、兵革、病事による改元',
  },
  {
    age: '養和',
    name: '安徳天皇',
    years: 1181,
    reason: '安徳天皇践祚による改元',
  },
  {
    age: '治承',
    name: '高倉天皇',
    years: 1177,
    reason: '大極殿の火災、天変による改元',
  },
  {
    age: '安元',
    name: '高倉天皇',
    years: 1175,
    reason: '疱瘡の流行による改元',
  },
  {
    age: '承安',
    name: '高倉天皇',
    years: 1171,
    reason: '災変、厄会による改元',
  },
  {
    age: '嘉応',
    name: '高倉天皇',
    years: 1169,
    reason: '高倉天皇践祚による改元',
  },
  {
    age: '仁安',
    name: '六条天皇',
    years: 1166,
    reason: '六条天皇践祚による改元',
  },
  {
    age: '永万',
    name: '二条天皇',
    years: 1165,
    reason: '天変、怪異、疾疫などによる改元',
  },
  {
    age: '長寛',
    name: '二条天皇',
    years: 1163,
    reason: '天変、疱瘡による改元',
  },
  {
    age: '応保',
    name: '二条天皇',
    years: 1161,
    reason: '疱瘡の流行による改元',
  },
  {
    age: '永暦',
    name: '二条天皇',
    years: 1160,
    reason: '兵乱による改元',
  },
  {
    age: '平治',
    name: '二条天皇',
    years: 1159,
    reason: '二条天皇せ践祚による改元',
  },
  {
    age: '保元',
    name: '後白河天皇',
    years: 1156,
    reason: '後白河天皇践祚による改元',
  },
  {
    age: '久寿',
    name: '近衛天皇',
    years: 1154,
    reason: '変異、厄運による改元',
  },
  {
    age: '仁平',
    name: '近衛天皇',
    years: 1151,
    reason: '彗星の出現による改元',
  },
  {
    age: '久安',
    name: '近衛天皇',
    years: 1145,
    reason: '彗星の出現による改元',
  },
  {
    age: '天養',
    name: '近衛天皇',
    years: 1144,
    reason: '甲子革令による改元',
  },
  {
    age: '康治',
    name: '近衛天皇',
    years: 1142,
    reason: '近衛天皇践祚による改元',
  },
  {
    age: '永治',
    name: '崇徳天皇',
    years: 1141,
    reason: '辛酉革命による改元',
  },
  {
    age: '保延',
    name: '崇徳天皇',
    years: 1135,
    reason: '飢饉、疫疾、洪水による改元',
  },
  {
    age: '長承',
    name: '崇徳天皇',
    years: 1132,
    reason: '疾疫、怪異による改元',
  },
  {
    age: '天承',
    name: '崇徳天皇',
    years: 1131,
    reason: '炎旱、天変による改元',
  },
  {
    age: '大治',
    name: '崇徳天皇',
    years: 1126,
    reason: '疱瘡の流行による改元',
  },
  {
    age: '天治',
    name: '崇徳天皇',
    years: 1124,
    reason: '崇徳天皇践祚による改元',
  },
  {
    age: '保安',
    name: '鳥羽天皇',
    years: 1120,
    reason: '天変、厄運による改元',
  },
  {
    age: '元永',
    name: '鳥羽天皇',
    years: 1118,
    reason: '天変、疾疫による改元',
  },
  {
    age: '永久',
    name: '鳥羽天皇',
    years: 1113,
    reason: '天変、兵革、疫疾などによる改元',
  },
  {
    age: '天永',
    name: '鳥羽天皇',
    years: 1110,
    reason: '彗星の出現による改元',
  },
  {
    age: '天仁',
    name: '鳥羽天皇',
    years: 1108,
    reason: '鳥羽天皇践祚による改元',
  },
  {
    age: '嘉承',
    name: '堀河天皇',
    years: 1106,
    reason: '彗星による改元',
  },
  {
    age: '長治',
    name: '堀河天皇',
    years: 1104,
    reason: '天変による改元',
  },
  {
    age: '康和',
    name: '堀河天皇',
    years: 1099,
    reason: '地震（康和地震）、疾病による改元',
  },
  {
    age: '承徳',
    name: '堀河天皇',
    years: 1097,
    reason: '天変、地震による改元',
  },
  {
    age: '永長',
    name: '堀河天皇',
    years: 1097,
    reason: '天変、地震（永長地震）による改元',
  },
  {
    age: '嘉保',
    name: '堀河天皇',
    years: 1095,
    reason: '疱瘡の流行による改元',
  },
  {
    age: '寛治',
    name: '堀河天皇',
    years: 1087,
    reason: '堀河天皇践祚による改元',
  },
  {
    age: '応徳',
    name: '白河天皇',
    years: 1084,
    reason: '甲子革令による改元',
  },
  {
    age: '永保',
    name: '白河天皇',
    years: 1081,
    reason: '辛酉革命による改元',
  },
  {
    age: '承歴',
    name: '白河天皇',
    years: 1077,
    reason: '旱魃、疱瘡の流行による改元',
  },
  {
    age: '承保',
    name: '白河天皇',
    years: 1074,
    reason: '白河天皇践祚、三合厄による改元',
  },
  {
    age: '延久',
    name: '後三条天皇',
    years: 1069,
    reason: '後三条天皇践祚による改元',
  },
  {
    age: '治暦',
    name: '後冷泉天皇',
    years: 1065,
    reason: '旱魃、三合厄による改元',
  },
  {
    age: '康平',
    name: '後冷泉天皇',
    years: 1058,
    reason: '大極殿、法成寺の火災による改元',
  },
  {
    age: '天喜',
    name: '後冷泉天皇',
    years: 1053,
    reason: '天変、怪異による改元',
  },
  {
    age: '永承',
    name: '後冷泉天皇',
    years: 1046,
    reason: '後冷泉天皇践祚による改元',
  },
  {
    age: '寛徳',
    name: '後朱雀天皇',
    years: 1044,
    reason: '疾疫、干魃による改元',
  },
  {
    age: '長久',
    name: '後朱雀天皇',
    years: 1040,
    reason: '災変、内裏焼失による改元',
  },
  {
    age: '長暦',
    name: '後朱雀天皇',
    years: 1037,
    reason: '後朱雀天皇践祚による改元',
  },
  {
    age: '長元',
    name: '後一条天皇',
    years: 1028,
    reason: '疫病、炎旱による改元',
  },
  {
    age: '万寿',
    name: '後一条天皇',
    years: 1024,
    reason: '甲子革令による改元',
  },
  {
    age: '治安',
    name: '後一条天皇',
    years: 1021,
    reason: '辛酉革命による改元',
  },
  {
    age: '寛仁',
    name: '後一条天皇',
    years: 1017,
    reason: '後一条天皇践祚による改元',
  },
  {
    age: '長和',
    name: '三条天皇',
    years: 1013,
    reason: '三条天皇践祚による改元',
  },
  {
    age: '寛弘',
    name: '一条天皇',
    years: 1004,
    reason: '天変地妖による改元',
  },
  {
    age: '長保',
    name: '一条天皇',
    years: 999,
    reason: '天変、炎旱による改元',
  },
  {
    age: '長徳',
    name: '一条天皇',
    years: 995,
    reason: '疾疫、天変による改元',
  },
  {
    age: '正暦',
    name: '一条天皇',
    years: 990,
    reason: '大風、天変による改元',
  },
  {
    age: '永祚',
    name: '一条天皇',
    years: 989,
    reason: '彗星、地震など天変災異による改元',
  },
  {
    age: '永延',
    name: '一条天皇',
    years: 987,
    reason: '一条天皇践祚による改元',
  },
  {
    age: '寛和',
    name: '花山天皇',
    years: 985,
    reason: '花山天皇践祚による改元',
  },
  {
    age: '永観',
    name: '円融天皇',
    years: 983,
    reason: '干魃、皇居火災などによる改元',
  },
  {
    age: '天元',
    name: '円融天皇',
    years: 978,
    reason: '災変、陽五厄による改元',
  },
  {
    age: '貞元',
    name: '円融天皇',
    years: 976,
    reason: '火災、地震による改元',
  },
  {
    age: '天延',
    name: '円融天皇',
    years: 974,
    reason: '天変、地震による改元',
  },
  {
    age: '天禄',
    name: '円融天皇',
    years: 970,
    reason: '円融天皇践祚による改元',
  },
  {
    age: '安和',
    name: '冷泉天皇',
    years: 968,
    reason: '冷泉天皇践祚による改元',
  },
  {
    age: '康保',
    name: '村上天皇',
    years: 964,
    reason: '甲子革令、旱魃による改元',
  },
  {
    age: '応和',
    name: '村上天皇',
    years: 961,
    reason: '辛酉革命、皇居火災などによる改元',
  },
  {
    age: '天徳',
    name: '村上天皇',
    years: 957,
    reason: '水旱による改元',
  },
  {
    age: '天歴',
    name: '村上天皇',
    years: 947,
    reason: '村上天皇践祚による改元',
  },
  {
    age: '天慶',
    name: '朱雀天皇',
    years: 938,
    reason: '厄運、地震、御慎による改元',
  },
  {
    age: '承平',
    name: '朱雀天皇',
    years: 931,
    reason: '朱雀天皇践祚による改元',
  },
  {
    age: '延長',
    name: '醍醐天皇',
    years: 923,
    reason: '水潦、疾疫による改元',
  },
  {
    age: '延喜',
    name: '醍醐天皇',
    years: 901,
    reason: '辛酉革命、天変による改元',
  },
  {
    age: '昌泰',
    name: '醍醐天皇',
    years: 898,
    reason: '醍醐天皇践祚による改元',
  },
  {
    age: '寛平',
    name: '宇多天皇',
    years: 889,
    reason: '宇多天皇践祚による改元',
  },
  {
    age: '仁和',
    name: '光考天皇',
    years: 885,
    reason: '光孝天皇践祚による改元',
  },
  {
    age: '元慶',
    name: '陽成天皇',
    years: 877,
    reason: '陽成天皇践祚、<br>白雉・白鹿献上の瑞祥による改元',
  },
  {
    age: '貞観',
    name: '清和天皇',
    years: 859,
    reason: '清和天皇践祚による改元',
  },
  {
    age: '天安',
    name: '文徳天皇',
    years: 857,
    reason: '美作国・常陸国両国より<br>白鹿、連理の樹が献上された祥瑞による改元',
  },
  {
    age: '斉衡',
    name: '文徳天皇',
    years: 854,
    reason: '石見国から醴泉の瑞を<br>献上された事による改元',
  },
  {
    age: '仁寿',
    name: '文徳天皇',
    years: 851,
    reason: '文徳天皇即位、<br>白亀・甘露の瑞祥による改元',
  },
  {
    age: '嘉祥',
    name: '仁明天皇',
    years: 848,
    reason: '豊後国から白亀が献じられた瑞祥による改元',
  },
  {
    age: '承和',
    name: '仁明天皇',
    years: 834,
    reason: '仁明天皇践祚による改元',
  },
  {
    age: '天長',
    name: '淳和天皇',
    years: 824,
    reason: '淳和天皇践祚による改元',
  },
  {
    age: '弘仁',
    name: '嵯峨天皇',
    years: 810,
    reason: '嵯峨天皇践祚による改元',
  },
  {
    age: '大同',
    name: '平城天皇',
    years: 806,
    reason: '平城天皇践祚による改元',
  },
  {
    age: '延暦',
    name: '桓武天皇',
    years: 782,
    reason: '桓武天皇践祚による改元',
  },
  {
    age: '天応',
    name: '光仁天皇',
    years: 781,
    reason: '美雲の祥瑞による改元',
  },
  {
    age: '宝亀',
    name: '光仁天皇',
    years: 770,
    reason: '肥後国より白亀が<br>献上された祥瑞による改元',
  },
  // {
  //   "age": "神護景雲",
  //   "name": "称徳天皇",
  //   "years": "767",
  //   "reason": "慶雲の祥瑞による改元"
  // },
  // {
  //   "age": "天平神護",
  //   "name": "称徳天皇",
  //   "years": "765",
  //   "reason": "称徳天皇即位による改元"
  // },
  // {
  //   "age": "天平宝字",
  //   "name": "考謙天皇",
  //   "years": "757",
  //   "reason": "宮中で蚕が「五月八日開下帝釋標知天皇命百年息」<br>の文字を成し、駿河国でも瑞字を生じた祥瑞による改元"
  // },
  // {
  //   "age": "天平勝宝",
  //   "name": "考謙天皇",
  //   "years": "749",
  //   "reason": "孝謙天皇即位による改元"
  // },
  // {
  //   "age": "天平感宝",
  //   "name": "聖武天皇",
  //   "years": "749",
  //   "reason": "陸奥国から黄金を<br>献上された祥瑞による改元"
  // },
  {
    age: '天平',
    name: '聖武天皇',
    years: 729,
    reason: '左京職が背に「天王貴平知百年」<br>と文のある亀を献上した祥瑞による改元',
  },
  {
    age: '神亀',
    name: '聖武天皇',
    years: 724,
    reason: '白亀を献上された祥瑞による改元',
  },
  {
    age: '養老',
    name: '元正天皇',
    years: 717,
    reason: '美濃国の美泉の祥瑞による改元',
  },
  {
    age: '霊亀',
    name: '元正天皇',
    years: 715,
    reason: '元正天皇	元正天皇の即位、<br>左京職より瑞亀が献上された祥瑞による改元',
  },
  {
    age: '和銅',
    name: '元明天皇',
    years: 708,
    reason: '武蔵国より和銅が献上された祥瑞による改元',
  },
  {
    age: '慶雲',
    name: '文武天皇',
    years: 704,
    reason: '西楼上に慶雲を見た祥瑞による改元',
  },
  {
    age: '大宝',
    name: '文武天皇',
    years: 701,
    reason: '対馬国から金が献上された事による改元',
  },
  {
    age: '朱鳥',
    name: '天武天皇',
    years: 686,
    reason: '(不明)',
  },
  {
    age: '白雉',
    name: '考徳天皇',
    years: 650,
    reason: '穴戸国の国司が<br>白雉を献上した祥瑞による改元',
  },
  {
    age: '大化',
    name: '考徳天皇',
    years: 645,
    reason: '天下安寧、政化敷行による改元',
  },
];
